# adopted from https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
language: android

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.0-rc2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

    - sys-img-armeabi-v7a-android-25 #system image for emulator used
                                     #to run UI Tests

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  - "rm -f $HOME/.gradle/caches/modules-2/modules-2.lock"
before_install:
  - "chmod +x gradlew"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build connectedCheck --stacktrace

jdk:
  - oraclejdk8  # lamba expression support
